### ISSUE TITLE
Is it possible to add button when menu is already set to builder?

### ISSUE THREAD

**Issue by androlizer** [Kennyc1012/BottomSheet#10]

**Comment by Kennyc1012** [comment]
No, when setting a menu resource, all buttons are ignored. If you wanted to achieve this, you would need to use a custom view and customize it yourself.

**Comment by androlizer** [comment]
Very thank you for this quick turn around, can we consider to add some more actionable button like in this http://i.imgur.com/5U3eTFs.png image, and how may i forgot to thankyou for the wonderful work. Thanks very much.

**Comment by Kennyc1012** [comment]
If the buttons were to be anywhere, they would be at the bottom like they are [here](http://i.imgur.com/lR8SvTu.jpeg). I have no plans on doing this myself, but am open to a pull request.
