### ISSUE TITLE
Customize Size

### ISSUE THREAD

**Issue by swotino** [Kennyc1012/BottomSheet#14]
I define custom width in XML view, but it not work.
<LinearLayout... android:layout_width="XXXdp" ... />
Is there an other way to do that?

**Comment by Kennyc1012** [comment]
There are currently some limitations when using a custom view, see the README.


There are a few limitations when using a custom view. First, it MUST have a background set or it will appear transparent. Second, the root layout dimensions should always be ```layout_width="match_parent``` and ```layout_height="wrap_content```. Lastly, you will need to manage any click events as the BottomSheetListener can not determine anything from your custom view. If setting a custom view, all other builder settings will be ignored.

**Comment by Ivolian** [comment]
@Kennyc1012  
Wrap_content not work for recycleview when using a custom view.

**Comment by Kennyc1012** [comment]
The latest support library (V23.2.1) support wrap_content for recyclerviews.
