### ISSUE TITLE
Show both a message and a menu?

### ISSUE THREAD

**Issue by thorinside** [Kennyc1012/BottomSheet#16]
I wonder if it would be possible to build a bottomsheet with both the message (would be displayed at the top) and the menu (would be displayed below the message). I've been asked to have both a title and a short description message within the bottomsheet.

**Comment by Kennyc1012** [comment]
With the current setup, no. You can achieve this by setting a custom view. But you would have to manage everything yourself (setting up the adapter, click events, styles, etc...)

**Comment by thorinside** [comment]
I found a dirty way to get this effect, by making a layout in my project called `bottom_sheet_layout.xml` and changing the layout to accommodate my description message above the menu. I read through your source code, and it might be nice to change it so that if menu AND message are set, use a third layout for the bottom sheet. If I have time, I may PR that some day.
