### ISSUE TITLE
In portrait mode, when it showing, it on the virtual button

### ISSUE THREAD

**Issue by shimika** [Kennyc1012/BottomSheet#17]
I think it maybe animate behind the virtual button.
I test it in Nexus 5x.

**Comment by Kennyc1012** [comment]
Not sure I understand the issue. I have a Nexus 5X and haven't seen any issues with it.

**Comment by shimika** [comment]
http://i.imgur.com/DeIlnYx.png

I want like top case, but this library is doing like bottom one.
This library is awesome but little bit sad when animate from bottom when phone has virtual keyboard.

**Comment by Kennyc1012** [comment]
I've been trying to find a way to get the dialog to animate behind the virtual buttons but am unable find a solution. In the mean time, you can change the animation style of the dialog by creating a new style and override the ```android:windowAnimationStyle``` attribute.

**Comment by shimika** [comment]
Thanks. When I find a solution, I'll send message again.
