### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by Touti1991** [Kennyc1012/BottomSheet#23]
When i switch from Left to right the icons appears in the right but the menu title and the BottomSheet Title is to left
how can i support RTL
thanks in advance.

**Comment by Kennyc1012** [comment]
There is currently no RTL support baked into the library. You would need to fork it and provide support yourself, it should be fairly easy, just need to modify the XML layouts. I will accept a pull request for this since I'm not sure when I can get around to doing it myself.

**Comment by Touti1991** [comment]
OK i will thanks @Kennyc1012

**Comment by Kennyc1012** [comment]
@Touti1991 Please check the latest version for RTL support. I have not tested it on any actual device/emulator, only in the layout previews.
