### ISSUE TITLE
Eclipse Setup

### ISSUE THREAD

**Issue by Pankaj0307** [Kennyc1012/BottomSheet#24]
How to use this library in Eclipse IDE? please help me in this.

**Comment by Kennyc1012** [comment]
Eclipse is not supported. If you want to import into Eclipse, you would need to download the project files and manually add them to your own project. I recommend switching to [Android Studio](http://tools.android.com/download).

**Comment by Pankaj0307** [comment]
Thank you very much for your response :)

On 5 February 2016 at 20:25, Kenny Campagna <notifications@github.com>
wrote:

> Eclipse is not supported. If you want to import into Eclipse, you would
> need to download the project files and manually add them to your own
> project. I recommend switching to Android Studio
> <http://tools.android.com/download>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kennyc1012/BottomSheet/issues/24#issuecomment-180388759>
> .
>



-- 
Thanks & Regards,
Pankaj Sharma,
Cont. : 91-8686810058
