### ISSUE TITLE
Number of columns if Grid?

### ISSUE THREAD

**Issue by brenntech** [Kennyc1012/BottomSheet#25]
Is there any way to set the number of columns using the grid? I have the same number of items like in the example. It doesnt look good having 4 icons on the first row and then 2 icons on the bottom row. Is there any settings I could change to set number of columns?

Thanks

**Comment by Kennyc1012** [comment]
Its modeled after the design guidelines found [here](http://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-modal-bottom-sheets) where it shows tablets having 4 icons in a row. However, I will update it to alter the logic to evenly distribute them based on the number of icons present

**Comment by brenntech** [comment]
Thank you.. really looking forward to that.

**Comment by Kennyc1012** [comment]
The way column count will work for grids is as followed:

You can set the number of columns via the builder by calling the ```setColumnCount(int count)``` method, or you can set it via a style by specifying the ``` <attr name="bottom_sheet_column_count" format="integer" />``` attribute 

If the column count isn't specified, it will be obtained based on the number of items to display. If there are 7 or more items or exactly 4 items, 4 columns will be shown. If 1,2,3 or 5 items are to be displayed, 3 columns will be shown.

These values are only used if using the Grid style. The list style still follows the same logic as before

**Comment by brenntech** [comment]
Wow! That was quick... thank you very much sir Kenny!
