### ISSUE TITLE
Is there a way to programatically dismiss the bottom sheet? 

### ISSUE THREAD

**Issue by kiaanpillay** [Kennyc1012/BottomSheet#26]
Hi, great library! I'd like to know if there is anyway to dismiss the dialog programmatically? I can't seem to find any bottomsheet.dismiss() or anything like that?

**Comment by Kennyc1012** [comment]
BottomSheet extends Dialog, so you can call the dismiss method on it just like any other dialog. 

```java
BottomSheet bottomSheet =  new BottomSheet.Builder(getActivity())
    ...
    ...
    .create();

bottomSheet.show();
...
...
bottomSheet.dismiss();
```

**Comment by kiaanpillay** [comment]
Works perfectly, thanks
