### ISSUE TITLE
Dismiss on Button Clicked

### ISSUE THREAD

**Issue by darkholiday** [Kennyc1012/BottomSheet#28]
I want to dismiss the bottomSheet when i click on a button to show another one.
In the current case the new one shows in front of the previous one.

**Comment by Kennyc1012** [comment]
Can you paste your code of how you are showing both BottomSheets?

**Comment by darkholiday** [comment]
I have already found a solution.

 BottomSheet.Builder appSheet = new BottomSheet.Builder(getContext());
 BottomSheet bSheet   = appSheet.create();
and then i use bSheet.show(); or bSheet.dismiss();

Thank you for your quick response.
