### ISSUE TITLE
Bug when trying to use BottomSheet

### ISSUE THREAD

**Issue by FlorentAnders** [Kennyc1012/BottomSheet#29]
Hey!

I've implemented a BottomSheet. But when I try to start it, this crash happens:

04-30 15:37:11.151 19805 19805 E AndroidRuntime: Process: com.fa.touch.app, PID: 19805
04-30 15:37:11.151 19805 19805 E AndroidRuntime: java.lang.ClassCastException: io.codetail.widget.RevealLinearLayout cannot be cast to com.kennyc.bottomsheet.CollapsingView
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at com.kennyc.bottomsheet.BottomSheet.initLayout(BottomSheet.java:252)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at com.kennyc.bottomsheet.BottomSheet.onCreate(BottomSheet.java:134)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at android.app.Dialog.dispatchOnCreate(Dialog.java:394)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at android.app.Dialog.show(Dialog.java:295)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at com.kennyc.bottomsheet.BottomSheet$Builder.show(BottomSheet.java:925)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at com.fa.touch.activity.BrowserActivity$3.onClick(BrowserActivity.java:145)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at android.view.View.performClick(View.java:5232)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:21290)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:168)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5821)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
04-30 15:37:11.151 19805 19805 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
0

Do you know where this is coming from?

**Comment by Kennyc1012** [comment]
Can you post the code that creates the BottomSheet.
