### ISSUE TITLE
supportsRtl

### ISSUE THREAD

**Issue by miladna7** [Kennyc1012/BottomSheet#31]
Hello dear.
is it possible for u to remove or change this line 
supportsRtl="true"
[(here)](https://github.com/Kennyc1012/BottomSheet/blob/master/library/src/main/AndroidManifest.xml)
from ur project?
i do not want to support RTL but i cant set it to false, because ur library set it true and for result android studio give me this:
```
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@supportsRtl value=(false) from AndroidManifest.xml:21:9-36
	is also present at [com.github.Kennyc1012:BottomSheet:2.1.1] AndroidManifest.xml:11:18-44 value=(true).
	Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:15:5-62:19 to override. 
```

**Comment by Kennyc1012** [comment]
Did you use the ```tools:replace="android:supportsRtl"``` like stated in the output? That should fix the issue.

**Comment by miladna7** [comment]
Yes indeed.
 but it give me:

```
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs
```

and in the log : 
```

6:54:15 PM Executing tasks: [:app:assembleDebug]
6:54:16 PM Gradle build finished with 1 error(s) in 1s 288ms
```

**Comment by Kennyc1012** [comment]
I got it working with the sample app

```xml
 <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
        android:supportsRtl="false"
        xmlns:tools="http://schemas.android.com/tools"
        tools:replace="android:supportsRtl">
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
```

Can you paste your application tag?

**Comment by miladna7** [comment]
So clearly the error are coming from my app.
i keep digging.
Thanks for such a quick response .

**Comment by miladna7** [comment]
OK dear, in my manifest tools
was  defined in the  manifest tag.
i saw u added in the application tag,  so change my manifest and add tools in application tag, help me to  get ride of the error.
thank u dear.

**Comment by Kennyc1012** [comment]
```xml
tools:replace="android:supportsRTL"
```

should be
```xml
tools:replace="android:supportsRtl"
```

Notice the 'l' and 't' are not capitalized in 'Rtl'

**Comment by miladna7** [comment]
thank u dear. sorry to take ur time.
