### ISSUE TITLE
Grid Menu Click

### ISSUE THREAD

**Issue by karopass** [Kennyc1012/BottomSheet#32]
Hi !
I am learning android and used your library, I have tried to make it as given information here. I have implemented code like below

`findViewById(R.id.butShare).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
            	new BottomSheet.Builder(QuoteViewActivity.this)
                .setSheet(R.menu.grid_sheet)
                .grid()
                .setTitle("Lets Some Fun")
                .setListener(this)
                .show();
            }
        });`
but I am getting error on **.setListener(this)** like this "The method setListener(BottomSheetListener) in the type BottomSheet.Builder is not applicable for the arguments (new View.OnClickListener(){})". I have tried to check your example but there no any information for make Grid Menu in Action. Please suggest me what I am missing ?
Thanks

**Comment by Kennyc1012** [comment]
the setListener method does not take a View.OnClickListener, it takes a [BottomSheetListener](https://github.com/Kennyc1012/BottomSheet/blob/master/library/src/main/java/com/kennyc/bottomsheet/BottomSheetListener.java)
