### ISSUE TITLE
How to Hide on Menu Click ?

### ISSUE THREAD

**Issue by karopass** [Kennyc1012/BottomSheet#33]
How can I hide BottomSheet on menu click ? I have made button for close BottomSheet, but I do not know How can I do it ?

**Comment by Kennyc1012** [comment]
When a menu item is clicked, the bottom sheet should hide automatically. Can you post your creation code

**Comment by karopass** [comment]
Yes sir ! Understood ! let me make it empty action for that menu :) Thanks for nice library.
