### ISSUE TITLE
Icons are displayed with a colored background when using createShareBottomSheet()

### ISSUE THREAD

**Issue by CeJienAJPC** [Kennyc1012/BottomSheet#36]
I am testing this library on a physical device with Android v17 (Jellybean). I am noticing 2 issues
1. The icons of Shae Intents are filled with some background color. I am attaching an image for reference. Please have a closer look at the icons of Gmail, SHAREit and TubeMate. All have a blue background instead of plain white.
2. The other issue is the icon size. They seem to appear small (I might be wrong, but probably not). I read this line "icons for a linear list styled BottomSheet should be 24dp", but...

![device-2016-07-16-234440](https://cloud.githubusercontent.com/assets/15603039/16896443/4a257ea0-4bb1-11e6-8f03-bb84dab3253e.png)

Regards

**Comment by Kennyc1012** [comment]
1. Is that blue color defined anywhere in your app theme?
2. The icons are pulled from the system packages, they are whatever size is provide, I don't have control over this.

**Comment by CeJienAJPC** [comment]
1. I haven't defined the blue color anywhere in my project. However, the blue color appears to be the background color for the apps displayed in Settings > Apps. This color is probably defined by the device manufacturer or the launcher app (not sure)
2. I can see that the second problem is related to the first problem. Resizing the app icon to fit the background might solve this issue.

Unfortunately, I am unable to run this project on an emulator (old PC). However, will run my project on yet another hardware and will let you know

Regards

**Comment by Kennyc1012** [comment]
I don't have access to any 4.2 devices so I am unable to test this. Are you able to run the sample app, and if so, does it happen there?

**Comment by CeJienAJPC** [comment]
The screenshot attached to this issue was taken when running the App on
device with jellybean version of Android. I tried running the dependency
using grid layout. The results were similar. As mentioned I will try to
attach a screenshot from devices running on higher version of Android ASAP

Regards
