### ISSUE TITLE
How to filter out specific built-in sharing Options

### ISSUE THREAD

**Issue by CeJienAJPC** [Kennyc1012/BottomSheet#37]
When using createShareBottomSheet(), many unnecessary built-in sharing options (like Bluetooth, WLAN-Direct, built-in QR code apps and much more) are displayed. I there any way I can filter out specific sharing options by mentioning their package name.

A similar feature is available with [BottomSheet library offered by Flipboard](https://github.com/Flipboard/bottomsheet)

If no such feature is available adding such a feature would be helpful for the developers

**Comment by Kennyc1012** [comment]
There is a way for it to include a specific Set of packages, see [here](https://github.com/Kennyc1012/BottomSheet/blob/master/library/src/main/java/com/kennyc/bottomsheet/BottomSheet.java#L414) but there isn't a way to exclude any currently.

**Comment by CeJienAJPC** [comment]
Oh, I see. Would be great, If you can add the feature (to exclude a list of apps) in the future builds.
Thanks for the response

Regards
