### ISSUE TITLE
FullScreen BottomSheet or BottomSheetFragment Behavior feature with close button

### ISSUE THREAD

**Issue by LOG-TAG** [Kennyc1012/BottomSheet#38]
We need FullScreen BottomSheet or BottomSheetFragment Behavior feature with close button 
Example:  

![screenshot_2016-10-20-16-57-05](https://cloud.githubusercontent.com/assets/1190344/19558411/0137a326-96e8-11e6-8ebd-be39d2be4dab.png)

**Comment by Kennyc1012** [comment]
This exists in the [design support library](https://developer.android.com/reference/android/support/design/widget/BottomSheetDialogFragment.html), will not implement.
