### ISSUE TITLE
Project not available on Gradle 

### ISSUE THREAD

**Issue by rathodchintan** [Kennyc1012/BottomSheet#40]
When I tried to integrate this library with below dependency line, it is giving me error.

> compile 'com.github.Kennyc1012.BottomSheet:2.3.1'

![image](https://cloud.githubusercontent.com/assets/4371780/20001922/446e288c-a2a4-11e6-994f-d3a7bd96e592.png)

**Comment by Kennyc1012** [comment]
Make sure you add `maven { url "https://jitpack.io" }` to your repositories tag in your gradle file.
