### ISSUE TITLE
Is it possible to remove android:supportsRtl="true" from your manifest?

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [Kennyc1012/BottomSheet#42]
Hello,
Is it possible to remove android:supportsRtl="true" from your manifest?
we use android:supportsRtl="false" in our manifest because set Rtl to true, make problems for our projects(we have 2 projects and in both of them we have this problem).
so now we can not add your library to gradle of our app and we should download it and add it as a module to our project.so we have problems with updates and ... .
android studio sets supportsRtl to true automatically when you create a new project. i want to see if it is possible for you to remove this field from your manifest.
thanks in advance.

**Comment by Kennyc1012** [comment]
I had someone request that the library support it, which is why it was added, see #23 . What you can do is remove the node via the `tools` attribute. See [this](http://www.myandroidsolutions.com/2014/04/10/android-gradle-manifest-merge/#.WLwz_jvysuU) article for a better explanation.
