### ISSUE TITLE
On Resume bottom sheet Hides and expands

### ISSUE THREAD

**Issue by paramarthasaha96** [Kennyc1012/BottomSheet#49]
when we pause the app and the resume it again the bottom sheet first disappears then reappears. Is it possible to keep it fixed unless canceled.

**Comment by Kennyc1012** [comment]
Can you post a snippet of your code where you are creating your BottomSheet? Also if possible, the entire class where this is happening

**Comment by paramarthasaha96** [comment]
schedule.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View arg0) {
                     new BottomSheet.Builder(getContext())
                        .setView(R.layout.layout_schedule)
                        .show();            }
        });
Here i created the bottomsheet this onClickListener is in a fragment. And this can be reproduced if u shpw the bottomsheet and then pause the app and resume it again from recent apps.

**Comment by Kennyc1012** [comment]
So this looks to be an issue with the `windowAnimationStyle` in the dialogs style running when resuming. Will further into for a fix.

**Comment by paramarthasaha96** [comment]
Hope you fix this soon. Will help me a lot since this happens with bottomsheetdialogfragment as well.

**Comment by paramarthasaha96** [comment]
Thanks for the fix so fast 👍

**Comment by javieranton** [comment]
This bug is still happening for the BottomSheetDialogFragment.

**Comment by tlgbltcn** [comment]
Hey @Kennyc1012,

This problem still happening. You can see the code I implemented.

```
abstract class BaseBottomSheetDialogFragmentIssue<DB: ViewDataBinding> : BottomSheetDialogFragment() {

    lateinit var binding: DB

    @get:LayoutRes
    abstract val layoutResource: Int

    override fun getTheme() = R.style.BottomSheetDialogTheme

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        binding = DataBindingUtil.inflate(LayoutInflater.from(context),layoutResource, null, false)
        return binding.root
    }

    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        binding.lifecycleOwner = this@BaseBottomSheetDialogFragmentIssue
        initViewModel()
        initView()
    }

    open fun initViewModel() {}

    open fun initView() {}
}

```
and then;
---------------------------------

```
class BatteryBottomSheetDialog: BaseBottomSheetDialogFragmentIssue<BottomsheetBatteryBinding>() {

    override val layoutResource: Int
        get() = R.layout.bottomsheet_battery

    override fun initView() {
        binding.dismiss.setOnClickListener {
            dismissAllowingStateLoss()
        }
    }

    companion object {
        fun newInstance() = BatteryBottomSheetDialog()
    }
}


```
and then call my bottom sheet dialog from  the fragment;

   ```
 private val batteryBottomSheetDialog: BatteryBottomSheetDialog by lazy {
        BatteryBottomSheetDialog.newInstance()
    }
    .......

    override fun onBatteryClick() {
        batteryBottomSheetDialog.show(requireFragmentManager(), TAG)
    }

```

**Comment by dshazly** [comment]
any solutions it's still happened when the app  come from the background the bottom sheet fragment not appear as expanded and display small area of view
