### ISSUE TITLE
Set click listener for customview buttons

### ISSUE THREAD

**Issue by paramarthasaha96** [Kennyc1012/BottomSheet#50]
So i have some buttons in my custom layout which i need to click to do some actions. Is it possible to do it and if yes how?

**Comment by Kennyc1012** [comment]
When creating a BottomSheet with a custom view, you can setup the view however you want, for example:

```java
View v = LayoutInflater.from(getContext()).inflate(R.layout.my_view,null);
v.findViewById(R.id.my_button).setOnClickListener(v->doSomething());

new BottomSheet.Builder(this)
    .setView(v)
    .show();
```

**Comment by paramarthasaha96** [comment]
Thanks for it closing the issue.
