### ISSUE TITLE
Create method for the builder is confusing

### ISSUE THREAD

**Issue by fnk0** [Kennyc1012/BottomSheet#6]
Thanks for the great library but just a small point that I've seen while using it. To build a bottom sheet the method name that you used is ```create()``` while the standard used by all the other Java/Android libraries is ```build()```

**Comment by Kennyc1012** [comment]
Although it might be the standard, it isn't always used. For example [Alert Dialog uses create](http://developer.android.com/reference/android/app/AlertDialog.Builder.html#create()) and [Snackbar uses make](https://developer.android.com/reference/android/support/design/widget/Snackbar.html#make(android.view.View, int, int)). You also don't really need to ever call the ```build()``` method when creating a BottomSheet. You can just call ```show()``` to immediately display it like so:
```java
new BottomSheet.Builder(getActivity(), R.menu.bottom_sheet)
  .setTitle(R.string.options)
  .setListener(myListener)
  .show();
  ```

 Calling ```build()``` yourself should really only be used if you need reference to the BottomSheet for whatever reason.
