### ISSUE TITLE
Project not available on jitpack.io

### ISSUE THREAD

**Issue by pushkarmoi** [Kennyc1012/BottomSheet#8]
Please fix it. I soooooo need this library!

**Comment by Kennyc1012** [comment]
I am not having a problem with it, can you paste your gradle file please.

**Comment by OmarBizreh** [comment]
Had the same issue, this from your ReadMe "compile 'com.github.Kennyc1012:BottomSheet:-2.1.2-g26cb036-1'" is not working, while this is working "compile 'com.github.Kennyc1012:BottomSheet:2.1.2"
